EXPOSURE_VALUE = -7
BINARY_THRESHOLD = 25
GAUSS_KERNEL = (15, 15)
MEDIAN_KERNEL = 25
MEDIAN_KERNEL_BODY = 45
SQUARE_ACTIVE_THRESHOLD = 90
ALPHA = 1.3
VELOCITY_THRESHOLD = 400
FRAME_AREA_THRESHOLD = 0.2
GAME_DIFF_THRESHOLD = 10
MEDIAN_FILTER = 3

THRESH_HEIGHT = 50
# TODO need to fix the jumping offset
OFFSET_HEIGHT = 0
THRESH_WIDTH = 100


# canny and Hough transform parameters
FIND_LINES_EPS = 0.4
CANNY_HIGH = 225
CANNY_LOW = 60
RHO = 1
THETA_RES = 180
HOUGHLINE_THRESHOLD = 20
MIN_LINE_LENGTH = 40 /400
MAX_LINE_GAP = 5

# FOR ONE PLAYER
# PUNCH_COUNTER = 4
# KICK_COUNTER = 4
# MOVE_COUNTER = 5
# SQUARE_ACTIVE_COUNT = 5
# CENTER_VEL_SIZE = 10

# FOR TWO PLAYERS
PUNCH_COUNTER = 1
KICK_COUNTER = 1
MOVE_COUNTER = 4
SQUARE_ACTIVE_COUNT = 5
CENTER_VEL_SIZE = 10