BINARY_THRESHOLD = 30
GAUSS_KERNEL = (15, 15)
MEDIAN_KERNEL = 11
SQUARE_ACTIVE_THRESHOLD = 40
ALPHA = 1
VELOCITY_THRESHOLD = 300


# canny and Hough transform parameters
FIND_LINES_EPS = 0.4
CANNY_HIGH = 225
CANNY_LOW = 50
RHO = 1
THETA_RES = 180
HOUGHLINE_THRESHOLD = 10
MIN_LINE_LENGTH = 30 /400
MAX_LINE_GAP = 5

# FOR ONE PLAYER
# PUNCH_COUNTER = 4
# KICK_COUNTER = 4
# MOVE_COUNTER = 5
# SQUARE_ACTIVE_COUNT = 5
# CENTER_VEL_SIZE = 10

# FOR TWO PLAYERS
PUNCH_COUNTER = 0
KICK_COUNTER = 0
MOVE_COUNTER = 0
SQUARE_ACTIVE_COUNT = 2
CENTER_VEL_SIZE = 10